service: bill-sender

provider:
  name: aws
  runtime: nodejs12.x
  role: ${ssm:/prod/lambda/role}
  environment:
    SNSTOPIC: ${ssm:/prod/serverless-bill-sender/sns-topic}

# you can overwrite defaults here
  region: us-east-1

functions:
  bill:
    handler: handler.bill
    events:
      - schedule: cron(0 15 ? * 7 *)
    tags:
      stage: production
      project: serverless-bill-sender